BF: wrap operations which might puke while storing/loading hdf5 with try: finally:
otherwise we might end up with:

IOError: Unable to truncate a file which is already open (File accessability: Unable to open file)

which is not intended I think ;-)