BF(minor): skip, don't crash test_tsboxplot if scipy is N/A
got while testing on squeeze chroot

  ======================================================================
  ERROR: Failure: RuntimeError (Required external 'scipy' was not found)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/pymodules/python2.6/nose/loader.py", line 379, in loadTestsFromName
      addr.filename, addr.module)
    File "/usr/lib/pymodules/python2.6/nose/importer.py", line 39, in importFromPath
      return self.importFromDir(dir_path, fqname)
    File "/usr/lib/pymodules/python2.6/nose/importer.py", line 86, in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20150323_211002/PyMVPA/mvpa2/tests/test_stats.py", line 22, in <module>
      from mvpa2.misc.stats import compute_ts_boxplot_stats
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20150323_211002/PyMVPA/mvpa2/misc/stats.py", line 15, in <module>
      if externals.exists('scipy', raise_=True):
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20150323_211002/PyMVPA/mvpa2/base/externals.py", line 638, in exists
      raise exception, "Required external '%s' was not found" % dep
  RuntimeError: Required external 'scipy' was not found