RF+ENH: Get rid of exception type and improve error message
ValueError: parameter 'C' cannot accept value `123.4` (value must be at most 10.0) [value must be convertible to type 'float', and value must be in range [0.0, 10.0]]