actually do not yet build-depend on python-pprocess
- not in Debian proper (already+yet or at all)
- leads to

test_custom_results_fx_logic:
AssertionError: File /tmp/test-slLX1c7emvpa+001 must have been processed by now

failure in cow chroots (TODO)