BR! RF+PL+NF: GPR has sensitivities for non-linear kernels as well now
PL: code reformatted a bit according to guidelines
RF: function specific only to __main__ code is moved there
BR: unittest fails with:

$> MVPA_SEED=1 make unittest
WARNING: Known dependency griddata is not present, thus not available.
 * Please note: warnings are printed only once, but underlying problem might occur many times *
..................................................................................................................................................E................
======================================================================
ERROR: testAnalyzerWithSplitClassifier (test_datameasure.SensitivityAnalysersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/raid/home/yoh/proj/pymvpa/pymvpa/tests/tests_warehouse.py", line 66, in do_sweep
    method(*args_, **kwargs_)
  File "/raid/home/yoh/proj/pymvpa/pymvpa/tests/test_datameasure.py", line 70, in testAnalyzerWithSplitClassifier
    map_ = sana(self.dataset)
  File "/raid/home/yoh/proj/pymvpa/pymvpa/mvpa/measures/base.py", line 337, in __call__
    clf.train(dataset)
  File "/raid/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/base.py", line 336, in train
    result = self._train(dataset)
  File "/raid/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/base.py", line 1588, in _train
    clf.train(split[0])
  File "/raid/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/base.py", line 336, in train
    result = self._train(dataset)
  File "/raid/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/gpr.py", line 242, in _train
    self._km_train_train = km_train_train = self.__kernel.compute(train_fv)
  File "/raid/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/kernel.py", line 403, in compute
    self.wdm2 = squared_euclidean_distance(data1, data2, weight=(self.length_scale**-2))
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/distance.py", line 180, in squared_euclidean_distance
    data1w = data1 * weight
ValueError: shape mismatch: objects cannot be broadcast to a single shape on clf = GPR(kernel=KernelSquaredExponential(length_scale=[ 8703.56416918  7450.72318375  9122.49081407  9567.64024672  9721.20978276
  9982.51984635  9981.32597298  9877.34328764  9738.90668223  9826.28533844
  9700.89496076  9677.96283402  9917.51483681  9819.17858959], sigma_f=0.000542317653514), sigma_noise=1.0026461312, enable_states=['training_confusion', 'log_marginal_likelihood'], descr='GPR(kernel='sqexp')')