BF: missing import necessary for eval from repr + use custom dataset instead of precrafted
precrafted dataset has .a which exposes numpy bug:
$> python -c "from numpy import *; print __version__; r=repr(array(['s', None])); print r; eval(r)"
1.3.0
array([s, None], dtype=object)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
NameError: name 's' is not defined

See http://projects.scipy.org/numpy/ticket/1361 for bugreport