RF: Explicit external rpy to disambiguate reported problem
TODO:
1. suppress RPy noise
2. version check for LARS. The one I had available 0.9.5-0.r2d.1
and it doesn't work:

$> python test_lars.py
RHOME= /usr/lib/R
RVERSION= 2.4.0
RVER= 2040
RUSER= /home/yoh
Loading Rpy version 2040 .. Done.
Creating the R object 'r' ..  Done
EE
======================================================================
ERROR: testLARS (__main__.LARSTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_lars.py", line 27, in testLARS
    clf.train(data)
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/classifier.py", line 245, in train
    result = self._train(dataset)
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa/clfs/lars.py", line 145, in _train
    use_Gram=self.__use_Gram)
RException: Error in function (x, y, type = c("lasso", "lar", "forward.stagewise"),  :
        unused argument(s) (normalize = TRUE, intercept = TRUE)