BF: check if rdist_gen is still available while testing for rdist stability
User reported the crash

$> PYTHONPATH=$PWD python -c 'import mvpa2.support.scipy.stats'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mvpa2/support/scipy/stats.py", line 62, in <module>
    if rdist.veccdf.nin == 1:
AttributeError: 'rdist_gen' object has no attribute 'veccdf'

but that code should not be executed on newer scipys (only on older ones with
misbehaving rdist), thus making sure that we do not even get there should resolve
this issue