BF: explicitly turn-off compression off for scalar datatypes
required for h5py >= 2.0.0; otherwise leads to:

ERROR: mvpa2.tests.test_hdf5.test_dataset_without_chunks
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/pymodules/python2.6/nose/case.py", line 187, in runTest
      self.test(*self.arg)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/tests/test_hdf5.py", line 156, in test_dataset_without_chunks
      save(ds, f.name, compression='gzip')
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/dataset.py", line 837, in save
      obj2hdf(hdf, dataset, name, compression=compression)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 601, in obj2hdf
      _seqitems_to_hdf(pieces[1], args, memo, **kwargs)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 397, in _seqitems_to_hdf
      obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 581, in obj2hdf
      noid=True, **kwargs)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 397, in _seqitems_to_hdf
      obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 575, in obj2hdf
      _seqitems_to_hdf(obj, grp, memo, **kwargs)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 397, in _seqitems_to_hdf
      obj2hdf(items, item, name=str(i), memo=memo, noid=noid, **kwargs)
    File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20111010_173301/PyMVPA/mvpa2/base/hdf5.py", line 486, in obj2hdf
      hdf.create_dataset(name, None, None, obj, **kwargs)
    File "/usr/lib/python2.6/dist-packages/h5py/_hl/group.py", line 69, in create_dataset
      dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    File "/usr/lib/python2.6/dist-packages/h5py/_hl/dataset.py", line 79, in make_new_dset
      shuffle, fletcher32, maxshape)
    File "/usr/lib/python2.6/dist-packages/h5py/_hl/filters.py", line 71, in generate_dcpl
      raise TypeError("Scalar datasets don't support chunk/filter options")
  TypeError: Scalar datasets don't support chunk/filter options