BF: make LDA/QDA robust for cases with degenerate covariance structure through using pinv in that case
was detected with

======================================================================
ERROR: test_values (mvpa2.tests.test_clf.ClassifiersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/testing/sweepargs.py", line 67, in do_sweep
    method(*args_, **kwargs_)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/tests/test_clf.py", line 637, in test_values
    _ = cv(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/base/learner.py", line 239, in __call__
    return super(Learner, self).__call__(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/base/node.py", line 97, in __call__
    result = self._call(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/measures/base.py", line 489, in _call
    return super(CrossValidation, self)._call(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/measures/base.py", line 318, in _call
    result = node(sds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/base/learner.py", line 239, in __call__
    return super(Learner, self).__call__(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/base/node.py", line 97, in __call__
    result = self._call(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/measures/base.py", line 583, in _call
    measure.train(dstrain)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/base/learner.py", line 119, in train
    result = self._train(ds)
  File "/home/neurodebian/proj/pymvpa/logs/daily/pymvpa_tests-20121121_134232/PyMVPA/mvpa2/clfs/gda.py", line 244, in _train
    % (e,)
DegenerateInputError: Data is probably singular, since inverse fails. Got Singular matrix