disable start_easy for error of which even google doesn't have a clue
https://travis-ci.org/PyMVPA/PyMVPA/builds/19780386
$ if [ ! -z  ]; then make coveragecmdline; fi
fatal: No names found, cannot describe anything.
I: testing start_easy cmdline example with coverage
ERROR: No value for objref '61682928' (LookupError)
make: *** [tcc-start_easy] Error 1