Assure no NaN returned from OneWayAnova. All NaNs are converted to 0s (what they should be imho anyways)
Otherwise it leads to a very strange unittest failure:
ERROR: testBasic (mvpa.tests.test_datameasure.SensitivityAnalysersTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "mtrand.pyx", line 1661, in mtrand.shuffle
TypeError: object of type 'numpy.int64' has no len()