NF: Able to build a binary installer under windows (with LIBSVM)
Added minimal copy of libsvm code to 3rd/ (please see README).
Examples are working under win32.
Unit tests pass, except for a stupid file access issue. Error is:

======================================================================
ERROR: testColumnDataFromFile (test_iohelpers.IOHelperTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Z:\michael\hacking\pymvpa.dev\tests\test_iohelpers.py", line 85, in test
ColumnDataFromFile
    os.remove(fpath)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\docume~1\\nobody\\locals~1\\temp\\testhvfhjpmvpa'
----------------------------------------------------------------------